### ISSUE TITLE
Refactor test_query_parsing file

### ISSUE THREAD

**Issue by ttt-77** [ddkang/aidb#141]
Doesn't have to be for this PR but can we do something like turning this into a dict? Seems a bit easier

_Originally posted by @ddkang in https://github.com/ddkang/aidb/pull/140#discussion_r1422710764_

**Comment by shubhankarunhale** [comment]
Hi @ttt-77 , Can I help with this?

**Comment by ttt-77** [comment]
Sure, please go ahead.

**Comment by shubhankarunhale** [comment]
#162  contains the required changes. @ttt-77 Can you please review?
