### ISSUE TITLE
Parsing error for logic operator in WHERE clause

### ISSUE THREAD

**Issue by ttt-77** [ddkang/aidb#143]
The related function is https://github.com/ddkang/aidb/blob/0d466fe3c44e17f467f0c7dcf10a14af9baa7a29/aidb/query/query.py#L181-L211

In WHERE clause, the AND operator has higher priority than OR operator. 
e.g. WHERE x_min > 600 OR objects00.frame > 700 AND x_min = 1 OR x_max = 1
the correct parsing result should be same as the  parsing result of 'WHERE x_min > 600 OR (objects00.frame > 700 AND x_min = 1) OR x_max = 1
However, current parsing result is same as 'WHERE ((x_min > 600 OR objects00.frame > 700) AND x_min = 1) OR x_max = 1'

To avoid this issue, please use () in WHERE clause for complex logic operation.

**Comment by ddkang** [comment]
@ttt-77 is this done?

**Comment by ttt-77** [comment]
No

**Comment by bhv7899** [comment]
Hi @ttt-77, can I try helping with this?

**Comment by ttt-77** [comment]
Sure
