### ISSUE TITLE
Not waiting for the insertion to complete in case of mysql

### ISSUE THREAD

**Issue by akash17mittal** [ddkang/aidb#28]
https://github.com/ddkang/aidb-new/blob/1f7021a67b507b4308f3f31c26b60989cb7ec93c/tests/db_utils/db_setup.py#L142

I have spent so much time on this but unable to figure out. The execution doesn't stop at this line for the insertion to complete in case of mysql.

**Comment by ttt-77** [comment]
Fixed in PR #151
