### ISSUE TITLE
Support Column Extraction on Nested Queries

### ISSUE THREAD

**Issue by akash17mittal** [ddkang/aidb#45]

**Comment by ttt-77** [comment]
Current code only supports such 'where(b.timestamp > 10 or c.color = red) and (b.timestamp < 12 or c.color = red)' clause. It doesn't support IN operator in WHERE clause. Need to refactor this function.
https://github.com/ddkang/aidb/blob/a25decc9dc1d1a77a93b1fab296acbc344d23bc3/aidb/query/query.py#L121
